"""End-to-end test of the Tracé SaaS on a local copy of the stack (see start-stack.sh).
Drives real browsers through: sign-in by email link and by password (sign-up, confirmation, reset,
changing it), Google/GitHub buttons, cloud saving, the free limit, sharing,
a second device, upgrading with a (fake) Paddle checkout and a signed webhook, the billing
portal, deleting, and signing out.

Run: python3 tests/e2e/e2e_test.py <path to MathJax tex-svg.js> <path to supabase-js dist/umd folder>
"""
import asyncio, hashlib, hmac, json, os, subprocess, sys, time, urllib.request, urllib.parse
from playwright.async_api import async_playwright

SITE = 'http://127.0.0.1:8788'
SB = 'http://127.0.0.1:54321'
DB = 'trace_e2e'
MJ, SBJS = sys.argv[1], sys.argv[2]
EMAIL = 'prof@uni.example'
KEYS = json.load(urllib.request.urlopen(SB + '/__test/keys'))

def sql(q):
    return subprocess.run(['psql', '-qAt', '-d', DB, '-c', q], capture_output=True, text=True, check=True).stdout.strip()

passed = []
def check(ok, what):
    if not ok:
        raise AssertionError('FAIL: ' + what)
    passed.append(what); print('  ok ', what, flush=True)

CONFIG = """window.TRACE_CONFIG = { supabaseUrl: '%s', supabaseAnonKey: '%s', signInWith: { google: false, github: false },
  paddleEnv: 'sandbox', paddleClientToken: 'test_client_token', prices: { monthly: 'pri_month', yearly: 'pri_year' },
  priceLabels: { monthly: '$8 a month', yearly: '$72 a year' }, freeDecks: 3 };""" % (SB, KEYS['anon'])
PADDLE_STUB = """window.Paddle = { Environment: { set(e) { window.__paddleEnv = e; } },
  Initialize(o) { window.__paddleInit = o; }, Checkout: { open(o) { window.__checkout = o; } } };"""

async def new_device(browser, errors, name, config=None):
    ctx = await browser.new_context(viewport={'width': 1440, 'height': 860}, color_scheme='dark')
    async def r_config(route): await route.fulfill(body=config or CONFIG, content_type='application/javascript')
    async def r_mj(route):   # MathJax and the extensions it loads next to itself
        rel = route.request.url.split('/es5/', 1)[1].split('?')[0]
        await route.fulfill(path=os.path.join(os.path.dirname(MJ), rel), content_type='application/javascript')
    async def r_sb(route): await route.fulfill(path=os.path.join(SBJS, route.request.url.rsplit('/', 1)[1]), content_type='application/javascript')
    async def r_paddle(route): await route.fulfill(body=PADDLE_STUB, content_type='application/javascript')
    await ctx.route(SITE + '/config.js', r_config)
    await ctx.route('https://cdn.jsdelivr.net/npm/mathjax@3.2.2/**', r_mj)
    await ctx.route('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.45.4/dist/umd/*', r_sb)
    await ctx.route('https://cdn.paddle.com/**', r_paddle)
    await ctx.route('https://customer-portal.paddle.example/**', lambda r: r.fulfill(body='<h1>Paddle customer portal (fake)</h1>', content_type='text/html'))
    await ctx.route('https://fonts.googleapis.com/**', lambda r: r.abort())
    await ctx.route('https://fonts.gstatic.com/**', lambda r: r.abort())
    await ctx.add_init_script("try{localStorage.setItem('trace-toured','1')}catch(e){}")   # skip the first-visit tour offer
    pg = await ctx.new_page()
    pg.on('pageerror', lambda e: errors.append(f'{name}: {e}'))
    pg.on('dialog', lambda d: asyncio.ensure_future(d.accept()))
    return ctx, pg

async def wait_for(pg, js, timeout=15000, what=''):
    try:
        await pg.wait_for_function(js, timeout=timeout)
    except Exception:
        raise AssertionError('FAIL (timed out): ' + (what or js))

async def email_link(pg, page, email):
    """Asks for a sign-in link on /signup or /login and follows it, like clicking the link in the email."""
    await pg.goto(SITE + page); await pg.wait_for_timeout(900)
    await use_link(pg)
    await pg.fill('#email', email)
    await pg.click('#sendBtn')
    await wait_for(pg, "document.body.innerText.includes('Check your inbox')", what='email sent')
    code = json.load(urllib.request.urlopen(SB + '/__test/code?email=' + urllib.parse.quote(email)))['code']
    sep = '&' if '?' in page else '?'
    await pg.goto(SITE + page + sep + 'code=' + code)

async def use_link(pg):
    """The sign-in pages open on email + password; switch to "Email me a link"."""
    if await pg.is_visible('#password'):
        await pg.click('#altMethod'); await pg.wait_for_timeout(150)

def code_for(email):
    return json.load(urllib.request.urlopen(SB + '/__test/code?email=' + urllib.parse.quote(email)))['code']

async def fill_profile(pg, name, role='teacher', subject='Physics', org='Lycée Ibn Sina'):
    await pg.wait_for_selector('#pf_name')
    await pg.fill('#pf_name', name)
    await pg.check(f'input[name=pf_role][value={role}]', force=True)
    if subject: await pg.fill('#pf_subject', subject)
    if org: await pg.fill('#pf_org', org)
    await pg.click('#pf_colors button:nth-child(3)')
    await pg.click('#pf_save')

async def sign_in(pg, new=False):
    if new:
        await email_link(pg, '/signup', EMAIL)
        await wait_for(pg, "document.body.innerText.includes('Tell us a little about you')", what='profile step')
        await fill_profile(pg, 'Prof Ada')
    else:
        await email_link(pg, '/login', EMAIL)
    await pg.wait_for_url('**/app', timeout=15000)
    await wait_for(pg, "window.__traceCloud && window.__traceCloud.state().user", what='signed in')

def webhook(event_type, status, user_id, occurred):
    body = json.dumps({'event_id': 'evt_' + str(time.time()), 'event_type': event_type, 'occurred_at': occurred,
                       'data': {'id': 'sub_e2e', 'status': status, 'customer_id': 'ctm_e2e', 'custom_data': {'user_id': user_id},
                                'current_billing_period': {'ends_at': '2026-11-09T12:00:00Z'}}})
    ts = str(int(time.time()))
    sig = hmac.new(b'pdl_ntfset_test_secret', f'{ts}:{body}'.encode(), hashlib.sha256).hexdigest()
    req = urllib.request.Request(SITE + '/api/paddle-webhook', data=body.encode(), method='POST',
                                 headers={'paddle-signature': f'ts={ts};h1={sig}', 'content-type': 'application/json'})
    return urllib.request.urlopen(req).status

async def main():
    errors = []
    async with async_playwright() as p:
        browser = await p.chromium.launch()

        print('Website')
        ctxW, W = await new_device(browser, errors, 'site')
        await W.goto(SITE + '/'); await W.wait_for_timeout(800)
        check('Slides where the maths' in await W.inner_text('h1'), 'the home page loads')
        await W.fill('#hRange', '2.7'); await W.dispatch_event('#hRange', 'input')
        check(await W.inner_text('#hKv') == '2.7' and await W.text_content('#hK') == '2.7', 'the live graph on the home page follows its slider')
        for _ in range(3): await W.click('#cNext'); await W.wait_for_timeout(1400)
        check('3 of 3' in await W.inner_text('#cCount') and await W.get_attribute('#cLab', 'opacity') == '1' and 'Start again' in await W.inner_text('#cNext'), 'the click-by-click demo builds its slide in three clicks')
        for path in ['/terms', '/privacy', '/refunds']:
            r = await W.goto(SITE + path)
            check(r.status == 200 and 'Paddle' in await W.inner_text('main'), f'{path} page exists and names Paddle as reseller')
        r = await W.goto(SITE + '/no-such-page')
        check(r.status == 404 and 'off the graph' in await W.inner_text('h1'), 'an unknown address shows the 404 page')
        for path in ['/robots.txt', '/sitemap.xml', '/site.webmanifest', '/img/og.png']:
            r = await W.goto(SITE + path)
            check(r.status == 200, f'{path} is served')
        r = await W.goto(SITE + '/')
        check('microphone=(self)' in (r.headers.get('permissions-policy') or 'microphone=(self)'), 'the site allows the microphone for voice recording')
        await W.goto(SITE + '/app?demo=showcase'); await W.wait_for_timeout(2500)
        check(not await W.is_hidden('#present') and await W.evaluate('deck.slides.length') == 14, 'the "Watch the tour" button plays the 14-slide tour')
        check(await W.evaluate("!localStorage.getItem('trace-projects') || !localStorage.getItem('trace-projects').includes('Tracé in motion')"), 'watching the tour saves nothing')
        await ctxW.close()

        print('Device A: not signed in')
        ctxA, A = await new_device(browser, errors, 'A')
        await A.goto(SITE + '/app#edit'); await A.wait_for_timeout(1500)
        check(await A.inner_text('#acctBtn') == 'Sign in', 'shows a Sign in button')
        check(await A.evaluate('deck.slides.length') > 0, 'the editor works without an account')
        check(sql('select count(*) from decks') == '0', 'nothing is uploaded before signing in')

        print('Device A: sign up on the sign-up page')
        await A.goto(SITE + '/'); await A.click('header >> text=Sign in'); await A.wait_for_timeout(600)
        check(A.url.endswith('/login'), 'Sign in on the home page opens the sign-in page')
        check(await A.is_visible('#password') and await A.is_visible('#forgot'), 'the sign-in page asks for email and password, with "Forgot password?"')
        await use_link(A)
        check(not await A.is_visible('#password') and 'link' in (await A.inner_text('#sendBtn')).lower(), '"Email me a sign-in link instead" switches to the no-password way')
        await A.fill('#email', EMAIL); await A.click('#sendBtn'); await A.wait_for_timeout(700)
        check('no account with this email' in (await A.inner_text('#emailErr')).lower(), 'signing in with an unknown email offers to create an account')
        await A.goto(SITE + '/signup'); await A.wait_for_timeout(600)
        await A.click('.plans-peek summary')
        check('Projects saved to your account' in await A.inner_text('.t-plans'), 'the sign-up page shows what Free and Pro include')
        await email_link(A, '/signup', EMAIL)
        await wait_for(A, "document.body.innerText.includes('Tell us a little about you')", what='profile step')
        check(True, 'after the email link, new people are asked for their profile')
        await A.click('#pf_save'); await A.wait_for_timeout(300)
        check('enter your name' in (await A.inner_text('#pf_err')).lower(), 'the profile needs a name')
        uid = sql(f"select id from auth.users where email = '{EMAIL}'")
        await A.goto(SITE + '/app#edit'); await A.wait_for_timeout(2500)
        check(await A.get_attribute('#cloudStat', 'title') == 'Finish your profile to save projects online', 'in the editor, an unfinished profile is pointed out')
        check(not await A.is_hidden('#cloudModal') and 'Finish your profile' in await A.inner_text('#cloudBody'), 'and the editor asks for it')
        check(sql(f"select count(*) from decks where owner = '{uid}'") == '0', 'nothing is saved online before the profile is complete')
        await fill_profile(A, 'Prof Ada')
        check(sql(f"select plan from profiles where id = '{uid}'") == 'free', 'a free account is created')
        await wait_for(A, "document.querySelector('#cloudStat').title === 'Saved to your account'", what='saved status')
        check(sql(f"select count(*) from decks where owner = '{uid}'") == '1', 'the project on this device is saved to the account')
        check(await A.inner_text('#acctBtn') == 'PA' and 'Prof Ada' in await A.get_attribute('#acctBtn', 'aria-label'), 'the account button shows the person\'s initials')
        check(sql(f"select display_name || '|' || role || '|' || subject || '|' || avatar_color from profiles where id = '{uid}'") == 'Prof Ada|teacher|Physics|#7a3b8f', 'the profile is saved with name, role, subject and colour')

        print('Device A: edits are saved online')
        await A.evaluate("snap(); deck.slides[0].objects.push(Object.assign(make('circle'), {id: 'e2e_circle', x: 1.5})); persist(); refresh();")
        await wait_for(A, "document.querySelector('#cloudStat').textContent.includes('Saved')", what='saved after edit')
        await A.wait_for_timeout(2600)
        check(sql(f"select count(*) from decks where owner = '{uid}' and data::text like '%e2e_circle%'") == '1', 'an edit reaches the database within a few seconds')
        await A.fill('#projName', 'Waves lecture'); await A.press('#projName', 'Enter'); await A.wait_for_timeout(1500)
        check(sql(f"select name from decks where owner = '{uid}'") == 'Waves lecture', 'renaming is saved online')

        print('Device A: the tutorial practice project stays on the device')
        mine = await A.evaluate("curProj")
        await A.evaluate("tourDeck('Tutorial practice', os => os.push(make('circle')))"); await A.wait_for_timeout(3000)
        check(sql(f"select count(*) from decks where owner = '{uid}'") == '1' and 'practice' in (await A.get_attribute('#cloudStat', 'title')).lower(), 'the tutorial’s practice project is not saved to the account')
        await A.evaluate(f"openProject('{mine}')"); await A.wait_for_timeout(800)

        print('Device A: the free plan keeps 3 decks')
        for i in range(3):
            await A.evaluate(f"createProject('Extra {i + 1}', blankDeck())")
            await A.wait_for_timeout(1300)
        await A.wait_for_timeout(1500)
        check(sql(f"select count(*) from decks where owner = '{uid}'") == '3', 'only 3 decks go to the cloud on Free')
        check('on this device only' in (await A.get_attribute('#cloudStat', 'title')).lower(), 'the 4th deck says it is on this device only')
        await wait_for(A, "!document.querySelector('#cloudModal').hidden", what='upgrade suggestion')
        check('Tracé Pro' in await A.inner_text('#cloudBody') and 'Unlimited' in await A.text_content('#cloudBody .t-plans'), 'an upgrade suggestion explains the limit and compares Free and Pro')
        await A.click('#cloudClose')

        print('Device A: share a deck')
        first = await A.evaluate("projects.find(p => p.name === 'Waves lecture').id")
        await A.evaluate(f"openProject('{first}')"); await A.wait_for_timeout(600)
        await A.click('#shareBtn')
        await wait_for(A, "!!document.querySelector('#shareOn')", what='share dialog')
        await A.check('#shareOn')
        await wait_for(A, "!!document.querySelector('#shareLink')", what='share link')
        link = await A.input_value('#shareLink')
        check('/v/' in link and len(link.rsplit('/', 1)[1]) == 12, 'a share link is created')
        check(await A.is_visible('#cloudBody .pro-tag'), 'the share window marks what Pro adds (no badge, view counts)')
        await A.click('#cloudClose')

        print('Viewer: anyone with the link')
        ctxV, V = await new_device(browser, errors, 'viewer')
        await V.goto(link.replace('http://127.0.0.1:8788', SITE)); await V.wait_for_timeout(2500)
        check(not await V.is_hidden('#present'), 'the link opens straight into the presentation')
        check(await V.is_visible('#present .badge'), 'free decks show the "Made with Tracé" badge')
        check(await V.evaluate("deck.slides[0].objects.some(o => o.id === 'e2e_circle')"), 'the viewer sees the latest version')
        check(await V.evaluate("projects.every(p => !p.cloudId)") and await V.evaluate("!localStorage.getItem('trace-projects').includes('e2e_circle')"), "the shared deck is not copied into the viewer's own projects")
        await V.click('#exitPres'); await V.wait_for_timeout(300)
        check(await V.is_visible('#vend'), 'closing shows an end card with "Make your own"')
        check('by Prof Ada' in await V.inner_text('#vend'), 'viewers see who made the deck')
        check(sql(f"select view_count from decks where share_slug = '{link.rsplit('/', 1)[1]}'") == '1', 'the view is counted')
        await V.goto(SITE + '/v/notarealslug1'); await V.wait_for_timeout(1500)
        check('not shared' in (await V.inner_text('#vend')).lower(), 'a wrong link explains itself')

        print('Interactive share links')
        await A.evaluate("""()=>{snap();const e=make('latex');e.id='e2e_eq';e.src='y = k x';e.params={k:1};e.live={k:{on:true,min:0,max:5}};e.y=2;slide().objects.push(e);syncAll();persist();refresh();}""")
        await A.wait_for_timeout(3500)
        await V.goto(link.replace('http://127.0.0.1:8788', SITE)); await V.wait_for_timeout(2500)
        check(await V.is_visible('#plive input') and not await V.evaluate("document.body.classList.contains('watch-only')"), 'by default, viewers get the live sliders')
        check(await V.is_visible('#vhint') and 'Try it' in await V.inner_text('#vhint'), 'a hint tells viewers they can drag the sliders')
        await V.evaluate("()=>{const i=document.querySelector('#plive input');setLv(i,3.5);}"); await V.wait_for_timeout(300)
        check(await V.evaluate("presOv.e2e_eq && presOv.e2e_eq.k === 3.5") and await V.evaluate("!document.querySelector('#plive .preset').classList.contains('off')"), 'moving a slider changes the maths, and a Reset button appears')
        await V.click('#pReset'); await V.wait_for_timeout(200)
        check(await V.evaluate("Object.keys(presOv).length === 0"), 'Reset puts the values back')
        check(not await V.is_visible('#vcopy'), 'copying is off unless the owner allows it')
        await A.click('#shareBtn'); await wait_for(A, "!!document.querySelector('#shareInter')", what='share options')
        check(await A.is_checked('#shareInter') and not await A.is_checked('#shareCopy'), 'the Share window shows what viewers may do (sliders on, copy off)')
        await A.uncheck('#shareInter'); await A.check('#shareCopy'); await A.wait_for_timeout(300)
        await A.click('#cloudClose'); await A.wait_for_timeout(3500)
        ctxV3, V3 = await new_device(browser, errors, 'viewer3')
        await V3.goto(link.replace('http://127.0.0.1:8788', SITE)); await V3.wait_for_timeout(2500)
        check(await V3.evaluate("document.body.classList.contains('watch-only')") and not await V3.is_visible('#plive'), 'a watch-only link hides the sliders')
        check(await V3.is_visible('#vcopy'), 'when allowed, viewers see "Make my own copy"')
        await V3.click('#vcopy'); await V3.wait_for_url('**/app#edit', timeout=10000); await V3.wait_for_timeout(2000)
        cp = await V3.evaluate("(()=>{const m=curMeta();return {name:m&&m.name, eq:deck.slides[0].objects.some(o=>o.id==='e2e_eq'), circ:deck.slides[0].objects.some(o=>o.id==='e2e_circle'), viewer:!!deck.viewer};})()")
        check(cp['name'] == 'Waves lecture (from Prof Ada)' and cp['eq'] and cp['circ'] and not cp['viewer'], f'the copy opens in the viewer\'s own editor, ready to change {cp}')
        check(sql(f"select count(*) from decks where owner = '{uid}' and data::text like '%e2e_eq%'") == '1', 'the owner\'s deck is unchanged by the copy')
        await A.click('#shareBtn'); await wait_for(A, "!!document.querySelector('#shareInter')", what='share options again')
        await A.check('#shareInter'); await A.uncheck('#shareCopy'); await A.wait_for_timeout(300); await A.click('#cloudClose'); await A.wait_for_timeout(3000)
        await ctxV3.close()

        print('Device B: same account on another computer')
        ctxB, B = await new_device(browser, errors, 'B')
        await sign_in(B)
        await B.wait_for_timeout(2500)
        names = await B.evaluate("projects.map(p => p.name)")
        check(all(n in names for n in ['Waves lecture', 'Extra 1', 'Extra 2']), 'decks saved on A appear on B')
        bid = await B.evaluate("projects.find(p => p.name === 'Waves lecture').id")
        await B.evaluate(f"openProject('{bid}')"); await B.wait_for_timeout(1500)
        check(await B.evaluate("deck.slides[0].objects.some(o => o.id === 'e2e_circle')"), 'opening a deck on B downloads its content')
        await B.evaluate("snap(); deck.slides[0].objects.push(Object.assign(make('rect'), {id: 'from_b'})); persist(); refresh();")
        await B.wait_for_timeout(3500)
        check(sql("select count(*) from decks where data::text like '%from_b%'") == '1', 'B saves its edit')
        await A.evaluate("window.__traceCloud.syncAll()"); await A.wait_for_timeout(2500)
        check(await A.evaluate("deck.slides[0].objects.some(o => o.id === 'from_b')"), 'A picks up the change made on B')

        print('Device A: Pro features on the free plan')
        check(await A.evaluate("PLAN.pro === false && PLAN.badge === true && !document.body.classList.contains('is-pro')"), 'the editor knows the account is on Free')
        await A.click('#tools >> text=3D'); await A.click('.menu:not([hidden]) [data-t="torus3"]')
        await wait_for(A, "!document.querySelector('#cloudModal').hidden", what='upgrade for 3D')
        body = await A.inner_text('#cloudBody')
        check('Advanced 3D' in body and 'Record your voice' in body, 'an advanced 3D object opens the Pro offer, which lists 3D and voice')
        await A.click('#cloudClose')
        check(not await A.evaluate("slide().objects.some(o => o.solids && o.solids.some(x => x.kind === 'torus'))"), 'the torus is not added on Free')
        await A.click('[data-menu="more"]'); await A.click('#exportBtn'); await A.wait_for_timeout(300)
        check(await A.evaluate("tab === 'json'"), 'Export opens the deck file on Free')
        await A.click('.tab[data-tab="code"]'); await A.wait_for_timeout(300)
        check('Python video script' in await A.inner_text('#cloudBody'), 'the Python video script asks for Pro')
        await A.click('#cloudClose'); await A.evaluate("document.querySelector('#modal').hidden = true")
        await A.click('[data-menu="more"]'); await A.click('#videoBtn'); await A.wait_for_timeout(300)
        check('Made with Tracé' in await A.inner_text('#vidBody') and await A.is_visible('#vidGo'), 'Make a video works on Free and says the video carries the badge')
        await A.click('#vidClose')
        await A.click('#presentBtn'); await A.wait_for_timeout(600)
        check(await A.is_visible('#pbadge'), 'presenting on Free shows "Made with Tracé"')
        await A.keyboard.press('Escape'); await A.wait_for_timeout(300)
        wid = await A.evaluate("projects.find(p => p.name === 'Waves lecture').id")
        await A.evaluate(f"openProject('{wid}')"); await A.wait_for_timeout(800)
        await A.evaluate("window.__clip = 'data:audio/webm;base64,GkXfo0AgQoaBAUL3gQFC8oEEQvOBCEKCQAR3ZWJtQoeBAkKFgQIYU4BnQI0VSalmQCgq17FAAw9CQE2AQAZ3aGFtbXlXQUAGd2hhbW15RIlACECPQAAAAAAAFlSua0AxrkAu14EBY8WBAZyBACK1nEADdW5khkAFVl9WUDglhohAA1ZQOIOBAeBABrCBCLqBCB9DtnVAIueBAKNAHIEAAIAwAQCdASoIAAgAAUAmJaQAA3AA/vz0AAA='; IMG.set('voice_e2e', __clip); idb.put('voice_e2e', __clip); snap(); deck.slides[0].voice = {0: {id: 'voice_e2e', dur: 2}}; persist(); refresh();")
        await A.wait_for_timeout(3000)
        check('pro feature' in (await A.get_attribute('#cloudStat', 'title')).lower(), 'a deck with recorded voice says it needs Pro')
        check(sql(f"select count(*) from decks where owner = '{uid}' and data::text like '%voice_e2e%'") == '0', 'recorded voice is not saved online on Free')

        print('Device A: upgrade to Pro (from the home page "Get Pro" button)')
        await A.goto(SITE + '/app?upgrade=1#edit'); await A.wait_for_timeout(2500)
        check(not await A.is_hidden('#cloudModal') and 'Tracé Pro' in await A.inner_text('#cloudBody'), '"Get Pro" opens the plan choice for a signed-in user')
        await A.click('#cloudBody [data-price="pri_year"]'); await A.wait_for_timeout(800)
        co = await A.evaluate("window.__checkout")
        check(co and co['items'][0]['priceId'] == 'pri_year' and co['customData']['user_id'] == uid and co['customer']['email'] == EMAIL, 'checkout opens with the price and the account id')
        check(await A.evaluate("window.__paddleEnv") == 'sandbox', 'Paddle runs in sandbox while testing')
        check(webhook('subscription.created', 'active', uid, '2026-10-09T15:00:00Z') == 200, 'the signed webhook is accepted')
        await A.evaluate("window.__paddleInit.eventCallback({ name: 'checkout.completed' })")
        await wait_for(A, "window.__traceCloud.state().profile && window.__traceCloud.state().profile.plan === 'pro'", 20000, 'Pro switched on')
        await A.wait_for_timeout(3000)
        check(sql(f"select plan from profiles where id = '{uid}'") == 'pro', 'the account is Pro in the database')
        check(sql(f"select count(*) from decks where owner = '{uid}'") == '4', 'the deck that was device-only is now saved online')
        check(sql(f"select count(*) from decks where owner = '{uid}' and data::text like '%voice_e2e%'") == '1', 'after upgrading, the deck with voice is saved online')
        check(await A.evaluate("PLAN.pro === true && PLAN.badge === false && document.body.classList.contains('is-pro')"), 'the editor unlocks the Pro features')
        await A.click('#presentBtn'); await A.wait_for_timeout(500)
        check(not await A.is_visible('#pbadge'), 'no badge while presenting on Pro')
        await A.keyboard.press('Escape'); await A.wait_for_timeout(200)
        await A.click('[data-menu="more"]'); await A.click('#videoBtn'); await A.wait_for_timeout(300)
        check('Made with Tracé' not in await A.inner_text('#vidBody'), 'Pro videos have no badge note')
        await A.click('#vidClose')
        await A.keyboard.press('Escape'); await A.wait_for_timeout(300)
        await A.evaluate("sel = null; addObj('torus3')")
        check(await A.evaluate("slide().objects.some(o => o.solids && o.solids.some(x => x.kind === 'torus'))"), 'Pro can add advanced 3D')
        await A.click('[data-menu="more"]'); await A.click('#exportBtn'); await A.wait_for_timeout(300)
        check(await A.evaluate("tab === 'code' && document.querySelector('#out').value.includes('class Presentation')"), 'Pro gets the Python video script')
        await A.evaluate("document.querySelector('#modal').hidden = true")
        await V.goto(link.replace('http://127.0.0.1:8788', SITE)); await V.wait_for_timeout(2000)
        check(not await V.is_visible('#present .badge'), 'Pro decks are shared without the badge')
        check(await V.evaluate("!!(deck.slides[0].voice && IMG.get(deck.slides[0].voice[0].id))"), 'viewers of a shared deck get its recorded voice')
        await A.evaluate("()=>{editStep=0;renderStepBar();}"); await A.click('#vDel'); await A.wait_for_timeout(3000)
        check(sql(f"select count(*) from decks where owner = '{uid}' and data::text like '%voice_e2e%'") == '0', 'deleting the voice clip saves the deck without it')

        print('Device A: billing portal')
        await A.click('#acctBtn')
        check('Pro plan' in await A.inner_text('#acctMenu'), 'the account menu says Pro')
        async with ctxA.expect_page() as newp:
            await A.click('[data-acct="billing"]')
        portal = await newp.value
        await portal.wait_for_load_state('commit')
        for _ in range(30):
            if 'customer-portal' in portal.url: break
            await A.wait_for_timeout(200)
        check('customer-portal.paddle.example/ctm_e2e' in portal.url, 'Manage billing opens the Paddle portal for this customer')
        await portal.close()

        print('Cancelling')
        check(webhook('subscription.canceled', 'canceled', uid, '2026-10-09T16:00:00Z') == 200, 'cancellation webhook accepted')
        check(sql(f"select plan from profiles where id = '{uid}'") == 'free', 'cancelling returns the account to Free')
        check(sql(f"select count(*) from decks where owner = '{uid}'") == '4', 'no deck is lost after cancelling')

        print('Account page')
        await B.goto(SITE + '/account'); await B.wait_for_timeout(2000)
        check('Prof Ada' in await B.inner_text('h1') and 'Free plan' in await B.inner_text('.plan-badge'), 'the account page shows the profile and plan')
        check('projects saved online' in await B.inner_text('main') and 'free plan keeps 3' in await B.inner_text('main'), 'it shows how much of the free plan is used')
        await B.fill('#pf_name', 'Ada Lovelace'); await B.click('#pf_save'); await B.wait_for_timeout(1200)
        check(sql(f"select display_name from profiles where id = '{uid}'") == 'Ada Lovelace', 'people can change their profile')
        await B.click('#signout'); await B.wait_for_timeout(1500)
        check('/login' in B.url, 'signing out on the account page goes to the sign-in page')
        await B.goto(SITE + '/app#edit'); await B.wait_for_timeout(2500)
        check(await B.evaluate("projects.every(p => !p.cloudId)"), 'and the next time the editor opens, the account\'s projects are gone from that browser')
        await B.goto(SITE + '/account'); await B.wait_for_timeout(1500)
        check('/login' in B.url, 'the account page needs you to be signed in')

        print('Device A: delete and sign out')
        extra = await A.evaluate("projects.find(p => p.name === 'Extra 3').id")
        await A.evaluate(f"openProject('{extra}')"); await A.wait_for_timeout(500)
        await A.evaluate("projAction('delete', {textContent: ''}).then(() => projAction('delete', {textContent: ''}))")
        await A.wait_for_timeout(1500)
        check(sql(f"select count(*) from decks where owner = '{uid}' and name = 'Extra 3'") == '0', 'deleting a project deletes its cloud copy')
        await A.click('#acctBtn'); await A.click('[data-acct="signout"]'); await A.wait_for_timeout(2000)
        check(await A.inner_text('#acctBtn') == 'Sign in', 'signed out')
        check(await A.evaluate("projects.every(p => !p.cloudId)"), "the account's decks are removed from this browser")
        check(sql(f"select count(*) from decks where owner = '{uid}'") == '3', 'and they are still safe in the account')

        print('Deleting an account')
        ctxD, D = await new_device(browser, errors, 'D')
        await email_link(D, '/signup', 'leaving@school.example')
        await fill_profile(D, 'Lea Ving', role='student', subject='', org='')
        await D.wait_for_url('**/app', timeout=15000); await D.wait_for_timeout(2500)
        did = sql("select id from auth.users where email = 'leaving@school.example'")
        check(sql(f"select count(*) from decks where owner = '{did}'") == '1', 'a new account saves its first project')
        await D.goto(SITE + '/account'); await D.wait_for_timeout(1500)
        await D.click('.danger-zone summary')
        check(await D.is_disabled('#delBtn'), 'deleting needs a confirmation tick first')
        await D.check('#delOk'); await D.click('#delBtn'); await D.wait_for_timeout(2000)
        check(sql(f"select count(*) from auth.users where id = '{did}'") == '0' and sql(f"select count(*) from decks where owner = '{did}'") == '0', 'people can delete their account and its projects')

        print('Passwords')
        PW_EMAIL = 'pw@school.example'
        ctxP, P = await new_device(browser, errors, 'P')
        await P.goto(SITE + '/signup'); await P.wait_for_timeout(800)
        check(await P.get_attribute('#password', 'autocomplete') == 'new-password' and await P.is_visible('#passwordMeter'), 'sign-up asks for a new password, with a strength meter')
        await P.fill('#email', PW_EMAIL); await P.fill('#password', 'short'); await P.click('#sendBtn'); await P.wait_for_timeout(300)
        check('at least 8' in (await P.inner_text('#emailErr')).lower(), 'a password under 8 characters is refused')
        await P.fill('#password', 'Correct horse battery 9')
        check(await P.get_attribute('#passwordMeter', 'data-s') in ('3', '4'), 'a long password shows as good or strong')
        await P.click('[data-eye="password"]')
        check(await P.get_attribute('#password', 'type') == 'text', 'the password can be shown')
        await P.click('#sendBtn')
        await wait_for(P, "document.body.innerText.includes('Check your inbox')", what='confirm sent')
        check('confirmation link' in await P.inner_text('main'), 'with a password, new accounts confirm their email first')
        await P.goto(SITE + '/login'); await P.wait_for_timeout(700)
        check(await P.is_visible('#password'), 'the sign-in page remembers the password method')
        await P.fill('#email', PW_EMAIL); await P.fill('#password', 'Correct horse battery 9'); await P.click('#sendBtn'); await P.wait_for_timeout(700)
        check('confirm your email' in (await P.inner_text('#emailErr')).lower() and await P.is_visible('#resendConfirm'), 'signing in before confirming explains it and offers to resend')
        await P.goto(SITE + '/signup?code=' + code_for(PW_EMAIL))
        await wait_for(P, "document.body.innerText.includes('Tell us a little about you')", what='profile after confirm')
        check(True, 'the confirmation link signs in and asks for the profile')
        await fill_profile(P, 'Pat Word', role='lecturer', subject='Maths', org='')
        await P.wait_for_url('**/app', timeout=15000)
        pid = sql(f"select id from auth.users where email = '{PW_EMAIL}'")
        check(sql(f"select display_name from profiles where id = '{pid}'") == 'Pat Word', 'the password account is created with its profile')
        await P.goto(SITE + '/account'); await P.wait_for_timeout(1500)
        check('Email and password' in await P.inner_text('#security') and 'Change your password' in await P.inner_text('#security'), 'the account page lists the ways to sign in')
        await P.click('#signout'); await P.wait_for_timeout(1500)
        await P.fill('#email', PW_EMAIL); await P.fill('#password', 'wrong password 1'); await P.click('#sendBtn'); await P.wait_for_timeout(700)
        check('wrong email or password' in (await P.inner_text('#emailErr')).lower(), 'a wrong password says so')
        await P.fill('#password', 'Correct horse battery 9'); await P.click('#sendBtn')
        await P.wait_for_url('**/app', timeout=15000)
        await wait_for(P, "window.__traceCloud && window.__traceCloud.state().user", what='signed in with password')
        check(True, 'signing in with email and password opens the editor')
        await P.evaluate("window.__traceCloud.signOut ? window.__traceCloud.signOut() : null"); await P.wait_for_timeout(500)

        print('Forgotten password')
        ctxR, R = await new_device(browser, errors, 'R')
        await R.goto(SITE + '/login'); await R.wait_for_timeout(700)
        await R.fill('#email', PW_EMAIL); await R.click('#forgot')
        check(await R.input_value('#email') == PW_EMAIL and 'Reset your password' in await R.inner_text('h1'), '"Forgot password?" keeps the email typed')
        await R.click('#resetBtn')
        await wait_for(R, "document.body.innerText.includes('Check your inbox')", what='reset sent')
        check('password reset link' in await R.inner_text('main'), 'a reset link is emailed')
        await R.goto(SITE + '/login?reset=1&code=' + code_for(PW_EMAIL))
        await wait_for(R, "document.body.innerText.includes('Choose a new password')", what='new password form')
        check('reset=1' in R.url and 'code=' not in R.url, 'the reset link opens "Choose a new password" and the code leaves the address')
        await R.fill('#newPassword', 'Correct horse battery 9'); await R.click('#savePw'); await R.wait_for_timeout(700)
        check('different' in (await R.inner_text('#emailErr')).lower(), 'the new password must differ from the old one')
        await R.fill('#newPassword', 'Purple tables dance 42'); await R.click('#savePw')
        await wait_for(R, "document.body.innerText.includes('Password saved')", what='password saved')
        check(True, 'the new password is saved')
        await R.click('#continueBtn'); await R.wait_for_url('**/app', timeout=15000)
        ctxR2, R2 = await new_device(browser, errors, 'R2')
        await R2.goto(SITE + '/login'); await R2.wait_for_timeout(700)
        await R2.fill('#email', PW_EMAIL); await R2.fill('#password', 'Correct horse battery 9'); await R2.click('#sendBtn'); await R2.wait_for_timeout(700)
        check('wrong email or password' in (await R2.inner_text('#emailErr')).lower(), 'the old password no longer works')
        await R2.fill('#password', 'Purple tables dance 42'); await R2.click('#sendBtn')
        await R2.wait_for_url('**/app', timeout=15000)
        check(True, 'the new password signs in')
        await R2.goto(SITE + '/account'); await R2.wait_for_timeout(1500); await R2.click('#signout'); await R2.wait_for_timeout(1200)
        await R2.goto(SITE + '/signup'); await R2.wait_for_timeout(700)
        await R2.fill('#email', PW_EMAIL); await R2.fill('#password', 'Another long one 77'); await R2.click('#sendBtn'); await R2.wait_for_timeout(700)
        check('already exists' in (await R2.inner_text('#emailErr')).lower(), 'signing up again with the same email points to sign in')

        print('Adding a password to an email-link account')
        ctxS, S = await new_device(browser, errors, 'S')
        await sign_in(S)
        await S.goto(SITE + '/account'); await S.wait_for_timeout(1500)
        check('Set a password' in await S.inner_text('#security'), 'an email-link account is offered to set a password')
        await S.fill('#acctPw', 'Ada counts engines 1843'); await S.click('#pwSave')
        await wait_for(S, "(document.querySelector('#flash:not([hidden])') || document.querySelector('#pwErr:not([hidden])') || {}).textContent", what='password result')
        check('password saved' in (await S.inner_text('#flash')).lower() and 'Change your password' in await S.inner_text('#security'), 'the password is saved from the account page, which now offers to change it')
        ctxS2, S2 = await new_device(browser, errors, 'S2')
        await S2.goto(SITE + '/login'); await S2.wait_for_timeout(700)
        await S2.fill('#email', EMAIL); await S2.fill('#password', 'Ada counts engines 1843'); await S2.click('#sendBtn')
        await S2.wait_for_url('**/app', timeout=15000)
        check(True, 'and it signs in on another device')

        print('Google and GitHub buttons, and expired links')
        social = CONFIG.replace("signInWith: { google: false, github: false }", "signInWith: { google: true, github: true }")
        ctxG, G = await new_device(browser, errors, 'G', social)
        await G.goto(SITE + '/login'); await G.wait_for_timeout(700)
        check(await G.is_visible('[data-provider="google"]') and await G.is_visible('[data-provider="github"]'), 'Google and GitHub buttons appear when switched on')
        await G.route(SB + '/auth/v1/authorize**', lambda r: r.fulfill(body='<h1>provider page (fake)</h1>', content_type='text/html'))
        await G.click('[data-provider="github"]'); await G.wait_for_url('**/auth/v1/authorize**', timeout=10000)
        q = urllib.parse.parse_qs(urllib.parse.urlparse(G.url).query)
        check(q.get('provider') == ['github'] and q.get('redirect_to', [''])[0].endswith('/login'), 'GitHub sign-in goes to the provider and comes back to Tracé')
        ctxN, N = await new_device(browser, errors, 'N')
        await N.goto(SITE + '/login'); await N.wait_for_timeout(700)
        check(not await N.is_visible('.social'), 'no social buttons until they are switched on')
        await N.goto(SITE + '/login?error=access_denied&error_code=otp_expired&error_description=Email+link+is+invalid+or+has+expired'); await N.wait_for_timeout(800)
        check('expired' in (await N.inner_text('#flash')).lower() and 'error' not in N.url, 'an expired link explains itself and the address is cleaned')
        for c in (ctxP, ctxR, ctxR2, ctxS, ctxS2, ctxG, ctxN): await c.close()

        print('Promo codes: free Pro, no card')
        sql("insert into promo_codes (code, days, max_uses, note) values ('FOUNDERS-TEST', 60, 2, 'e2e')")
        ctxT, T = await new_device(browser, errors, 'T')
        await email_link(T, '/signup', 'gift1@school.example'); await fill_profile(T, 'Gia Ft', role='teacher', subject='', org='')
        await T.wait_for_url('**/app', timeout=15000); await T.wait_for_timeout(1500)
        await T.goto(SITE + '/account'); await T.wait_for_timeout(1500)
        await T.click('#promo summary')
        await T.fill('#promoCode', 'NOPE-1234'); await T.click('#promoGo'); await T.wait_for_timeout(800)
        check('does not exist' in (await T.inner_text('#promoErr')).lower(), 'a wrong promo code is explained')
        await T.fill('#promoCode', 'founders-test'); await T.click('#promoGo')
        await wait_for(T, "document.querySelector('.plan-badge') && document.querySelector('.plan-badge').textContent === 'Pro'", what='gift pro')
        tid = sql("select id from auth.users where email = 'gift1@school.example'")
        check(sql(f"select plan || '|' || comp_code from profiles where id = '{tid}'") == 'pro|FOUNDERS-TEST', 'a promo code turns on Pro, with no card')
        check('Free with code FOUNDERS-TEST until' in await T.inner_text('#plan') and await T.is_visible('#upgradeLink') and not await T.is_visible('#billing'), 'the account page says until when, and offers to keep Pro after')
        await T.goto(SITE + '/app#edit'); await T.wait_for_timeout(2500)
        check(await T.evaluate("PLAN.pro === true"), 'the editor unlocks Pro for a promo code')
        await T.click('#acctBtn')
        check('Free with a code until' in await T.inner_text('#acctMenu') and not await T.is_visible('[data-acct="billing"]'), 'the account menu shows the free period, with no billing button')
        await T.keyboard.press('Escape')

        ctxU, U = await new_device(browser, errors, 'U')
        await U.goto(SITE + '/app?promo=FOUNDERS-TEST#edit'); await U.wait_for_timeout(2500)
        check('promo code FOUNDERS-TEST' in await U.inner_text('#cloudBody'), 'a promo link asks visitors to sign in to use the code')
        await email_link(U, '/signup?next=%2Fapp', 'gift2@school.example'); await fill_profile(U, 'Hal Two', role='student', subject='', org='')
        await U.wait_for_url('**/app', timeout=15000)
        await wait_for(U, "!document.querySelector('#cloudModal').hidden && document.querySelector('#promoCode') && document.querySelector('#promoCode').value === 'FOUNDERS-TEST'", what='promo prefilled')
        check(True, 'after signing up, the Pro window opens with the code filled in')
        await U.click('#promoGo')
        await wait_for(U, "PLAN.pro === true", 20000, 'pro from link')
        check(sql("select plan from profiles p join auth.users u on u.id = p.id where u.email = 'gift2@school.example'") == 'pro', 'one click on Redeem turns on Pro')

        ctxV2, V2 = await new_device(browser, errors, 'V2')
        await email_link(V2, '/signup?next=%2Faccount', 'gift3@school.example'); await fill_profile(V2, 'Ivy Three', role='student', subject='', org='')
        await V2.wait_for_url('**/account', timeout=15000); await V2.wait_for_timeout(1500)
        await V2.click('#promo summary'); await V2.fill('#promoCode', 'FOUNDERS-TEST'); await V2.click('#promoGo'); await V2.wait_for_timeout(800)
        check('already been used by everyone' in (await V2.inner_text('#promoErr')).lower(), 'the code stops after its 2 uses')

        sql(f"update profiles set comp_until = now() - interval '1 minute' where id = '{tid}'")
        await T.goto(SITE + '/account'); await T.wait_for_timeout(1800)
        check('Free plan' in await T.inner_text('.plan-badge') and sql(f"select plan from profiles where id = '{tid}'") == 'free', 'when the free months end, the account is back on Free')
        sql("insert into promo_codes (code, days, max_uses) values ('SECOND-CODE', 60, 5)")
        await T.click('#promo summary'); await T.fill('#promoCode', 'SECOND-CODE'); await T.click('#promoGo'); await T.wait_for_timeout(800)
        check('already used a promo code' in (await T.inner_text('#promoErr')).lower(), 'an account cannot use a second code')
        for c in (ctxT, ctxU, ctxV2): await c.close()

        print('Security from the browser')
        r = await V.evaluate("""async (k) => { const c = supabase.createClient('%s', k);
            const a = await c.from('decks').select('*'); const b = await c.rpc('apply_subscription', {p_user: null, p_customer: 'ctm_e2e', p_subscription: 's', p_status: 'active', p_renews_at: null, p_event_at: '2030-01-01'});
            return [a.error ? 'denied' : a.data.length, b.error ? 'denied' : 'allowed']; }""" % SB, KEYS['anon'])
        check(r == ['denied', 'denied'], 'a visitor with the public key can neither read decks nor grant Pro')

        check(not errors, 'no script errors: ' + '; '.join(errors))
        await browser.close()
    print(f'\nALL {len(passed)} END-TO-END CHECKS PASSED')

asyncio.run(main())
